#=============================================================
#          Character Killing Monuments (by paytaly)
# Para limpar as tabelas
# TRUNCATE character_kills_info;
# TRUNCATE character_kills_snapshot;
# Para testes: 150000 (5m) 600000 (10m) 1800000 (30m)
#=============================================================
# Enable the Character Killing Monuments
# Default: False
CKMEnabled = True

# The killing cycle length
# Default: 86400000 (24h)
CKMCycleLength = 1800000

# The title of the Monument for the PvP winner
# Note: %kills% will be replaced with the winner's PvP count in the cycle
# Default: %kills% PvPs in the last 24h
CKMPvPNpcTitle = %kills% PvPs in the last 24h

# The title color of the Monument for the PvP winner
# Default: 00CCFF (yellow)
CKMPvPNpcTitleColor = 00CCFF

# The name color of the Monument for the PvP winner
# Default: FFFFFF (white)
CKMPvPNpcNameColor = FFFFFF

# The title of the Monument for the PK winner
# Note: %kills% will be replaced with the winner's PK count in the cycle
# Default: %kills% PvPs in the last 24h
CKMPKNpcTitle = %kills% PKs in the last 24h

# The title color of the Monument for the PK winner
# Default: 00CCFF (yellow)
CKMPKNpcTitleColor = 00CCFF

# The name color of the Monument for the PK winner
# Default: FFFFFF (white)
CKMPKNpcNameColor = FFFFFF